-- ============================================================================
-- Area 34 schema + seed catch-up for an EXISTING PostgreSQL database
-- Mirrors migration: 20260802163432_AddSiteContentAndNoticeFields
--
-- WHY THIS FILE EXISTS
--   The app builds its schema with Database.EnsureCreated() (GHCAA.API/Program.cs:290),
--   which is a no-op once the database has any tables. Migrations are not run at
--   startup. So on preprod/Neon the SiteContents table and the three new NewsPosts
--   columns were never created, and /about silently falls back to its static markup.
--   Run this once against the preprod database to bring it level with the model.
--
-- SAFETY
--   Idempotent: re-running it changes nothing. Guarded by IF NOT EXISTS and
--   ON CONFLICT DO NOTHING; wrapped in a transaction.
--
-- USAGE
--   psql "<DATABASE_URL>" -f docs/sql/preprod_area34_sitecontent.sql
--   (Neon/Render external URLs need sslmode=require and an allow-listed source IP.)
--
-- NOTE
--   This does not write an __EFMigrationsHistory row, because a database created by
--   EnsureCreated has no migrations history to append to. See TODO 34.D9 for the
--   durable fix (switch runtime to Database.Migrate()).
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- 1. NewsPosts: News/Notice discriminator + PDF attachment columns
-- --------------------------------------------------------------------------
ALTER TABLE "NewsPosts" ADD COLUMN IF NOT EXISTS "AttachmentFileName" character varying(260) NULL;
ALTER TABLE "NewsPosts" ADD COLUMN IF NOT EXISTS "AttachmentUrl"      text                   NULL;
ALTER TABLE "NewsPosts" ADD COLUMN IF NOT EXISTS "PostType"           integer NOT NULL DEFAULT 0;  -- 0 = News, 1 = Notice

-- --------------------------------------------------------------------------
-- 2. SiteContents table
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "SiteContents" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY,
    "Key"              character varying(100) NOT NULL,
    "Group"            character varying(100) NOT NULL,
    "Title"            character varying(200) NOT NULL,
    "BodyHtml"         text                   NOT NULL,
    "DisplayOrder"     integer                NOT NULL,
    "IsActive"         boolean                NOT NULL,
    "LastModified"     timestamp with time zone NULL,
    "UpdatedByAdminId" integer                NULL,
    CONSTRAINT "PK_SiteContents" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_SiteContents_Key" ON "SiteContents" ("Key");

-- --------------------------------------------------------------------------
-- 3. Seed the five content blocks (constitution-sourced text only)
--    ON CONFLICT on the unique Key means admin edits are never overwritten.
-- --------------------------------------------------------------------------
INSERT INTO "SiteContents" ("Id", "BodyHtml", "DisplayOrder", "Group", "IsActive", "Key", "LastModified", "Title", "UpdatedByAdminId")
VALUES
(1, '<p>Govt. Haraganga College, Munshiganj, has stood as a centre of learning since 1938, founded through the initiative of Ashutosh Ganguly with the support of Sher-e-Bangla A. K. Fazlul Huq. Generations of students have passed through its halls and carried its name into public service, business, academia and the arts.</p><p>The Govt. Haraganga College Alumni Association exists to keep that lineage connected.</p>',
 1, 'about', true, 'about-origin', NULL, 'Our Origin', NULL),

(2, '<p>The organisation is named the <strong>Govt. Haraganga College Alumni Association (GHCAA)</strong>. Its members are known as <strong>HARAGANGIAN</strong>. The Association was founded on <strong>29 November 2025</strong>.</p><p>The Association is non-political, non-religious, inclusive and non-profit. It is a patron of education and culture and philanthropic in purpose. It does not affiliate with any political party or religious body, and welcomes all alumni without distinction.</p><p><strong>Motto:</strong> Sharing Heritage, Aligning Lives, Integrating Networks<br/><em>&#2405;&#2469;&#2495;&#2489;&#2509;&#2479;&#2503;&#2480; &#2476;&#2495;&#2472;&#2495;&#2478;&#2479;&#2492;, &#2460;&#2496;&#2476;&#2472;&#2503;&#2480; &#2488;&#2478;&#2472;&#2509;&#2476;&#2479;&#2492; &#2451; &#2488;&#2434;&#2489;&#2468;&#2495;&#2480; &#2488;&#2503;&#2468;&#2497;&#2476;&#2472;&#2509;&#2471;&#2472;</em></p>',
 2, 'about', true, 'about-association', NULL, 'The Association', NULL),

(3, '<p>Every element of the Association''s logo carries meaning:</p><ul><li><strong>Historic building</strong> &ndash; the college and its heritage</li><li><strong>Open book</strong> &ndash; knowledge and learning</li><li><strong>Torch</strong> &ndash; enlightenment and guidance</li><li><strong>Mortarboard</strong> &ndash; academic achievement</li><li><strong>Handshake</strong> &ndash; fellowship and mutual support among alumni</li><li><strong>Red and gold border, &ldquo;Est. 2025&rdquo;</strong> &ndash; the founding of the Association</li></ul><p>The Association''s flag is white, signifying peace, harmony, non-violence and purity.</p><p>Use of the Association''s name, logo, flag or other branding requires prior permission from the Executive Committee.</p>',
 3, 'about', true, 'about-logo', NULL, 'Logo & Flag', NULL),

(4, '<ul><li>To build and maintain a lasting bond among the alumni of Govt. Haraganga College.</li><li>To preserve and promote the heritage, history and traditions of the College.</li><li>To support the academic development of current students of the College.</li><li>To provide mentorship, career guidance and networking opportunities to students and alumni.</li><li>To assist alumni and students facing financial hardship through scholarships and welfare support.</li><li>To organise educational, cultural, social and sporting activities.</li><li>To encourage philanthropic and community service initiatives.</li><li>To strengthen cooperation between the Association, the College administration and its teachers.</li><li>To maintain an accurate register of alumni and facilitate communication among them.</li><li>To uphold transparency, accountability and good governance within the Association.</li><li>To undertake any other lawful activity consistent with these objectives.</li></ul>',
 4, 'about', true, 'about-objectives', NULL, 'Purpose & Objectives', NULL),

(5, '<p>The Association''s secretariat operates from the Govt. Haraganga College campus in Munshiganj. Reach us by email, phone, or the form below and a member of the Executive Committee will respond.</p>',
 1, 'contact', true, 'contact-intro', NULL, 'Get in Touch', NULL)
ON CONFLICT ("Key") DO NOTHING;

-- --------------------------------------------------------------------------
-- 4. Realign the identity sequence after the explicit-Id inserts above,
--    otherwise the first admin-created block collides on Id = 1.
-- --------------------------------------------------------------------------
SELECT setval(
    pg_get_serial_sequence('"SiteContents"', 'Id'),
    GREATEST((SELECT COALESCE(MAX("Id"), 1) FROM "SiteContents"), 1)
);

COMMIT;

-- --------------------------------------------------------------------------
-- Verification
-- --------------------------------------------------------------------------
-- SELECT "Id", "Key", "Group", "Title", "DisplayOrder", "IsActive" FROM "SiteContents" ORDER BY "Group", "DisplayOrder";
-- SELECT column_name FROM information_schema.columns
--  WHERE table_name = 'NewsPosts' AND column_name IN ('PostType','AttachmentUrl','AttachmentFileName');
