using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace GHCAA.Infrastructure.Data.Migrations.PgSql
{
    /// <inheritdoc />
    public partial class AddSiteContentAndNoticeFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"ALTER TABLE ""NewsPosts"" ADD COLUMN IF NOT EXISTS ""AttachmentFileName"" character varying(260);");

            migrationBuilder.Sql(@"ALTER TABLE ""NewsPosts"" ADD COLUMN IF NOT EXISTS ""AttachmentUrl"" text;");

            migrationBuilder.Sql(@"ALTER TABLE ""NewsPosts"" ADD COLUMN IF NOT EXISTS ""PostType"" integer NOT NULL DEFAULT 0;");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS ""SiteContents"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""Key"" character varying(100) NOT NULL,
                ""Group"" character varying(100) NOT NULL,
                ""Title"" character varying(200) NOT NULL,
                ""BodyHtml"" text NOT NULL,
                ""DisplayOrder"" integer NOT NULL,
                ""IsActive"" boolean NOT NULL,
                ""LastModified"" timestamp with time zone,
                ""UpdatedByAdminId"" integer,
                CONSTRAINT ""PK_SiteContents"" PRIMARY KEY (""Id"")
            );");

            migrationBuilder.Sql(@"DELETE FROM ""SiteContents"" WHERE ""Id"" IN (1, 2, 3, 4, 5);");

            migrationBuilder.InsertData(
                table: "SiteContents",
                columns: new[] { "Id", "BodyHtml", "DisplayOrder", "Group", "IsActive", "Key", "LastModified", "Title", "UpdatedByAdminId" },
                values: new object[,]
                {
                    { 1, "<p>Govt. Haraganga College, Munshiganj, has stood as a centre of learning since 1938, founded through the initiative of Ashutosh Ganguly with the support of Sher-e-Bangla A. K. Fazlul Huq. Generations of students have passed through its halls and carried its name into public service, business, academia and the arts.</p><p>The Govt. Haraganga College Alumni Association exists to keep that lineage connected.</p>", 1, "about", true, "about-origin", null, "Our Origin", null },
                    { 2, "<p>The organisation is named the <strong>Govt. Haraganga College Alumni Association (GHCAA)</strong>. Its members are known as <strong>HARAGANGIAN</strong>. The Association was founded on <strong>29 November 2025</strong>.</p><p>The Association is non-political, non-religious, inclusive and non-profit. It is a patron of education and culture and philanthropic in purpose. It does not affiliate with any political party or religious body, and welcomes all alumni without distinction.</p><p><strong>Motto:</strong> Sharing Heritage, Aligning Lives, Integrating Networks<br/><em>ঐতিহ্যের বিনিময়, জীবনের সমন্বয় ও সংহতির সেতুবন্ধন</em></p>", 2, "about", true, "about-association", null, "The Association", null },
                    { 3, "<p>Every element of the Association's logo carries meaning:</p><ul><li><strong>Historic building</strong> &ndash; the college and its heritage</li><li><strong>Open book</strong> &ndash; knowledge and learning</li><li><strong>Torch</strong> &ndash; enlightenment and guidance</li><li><strong>Mortarboard</strong> &ndash; academic achievement</li><li><strong>Handshake</strong> &ndash; fellowship and mutual support among alumni</li><li><strong>Red and gold border, &ldquo;Est. 2025&rdquo;</strong> &ndash; the founding of the Association</li></ul><p>The Association's flag is white, signifying peace, harmony, non-violence and purity.</p><p>Use of the Association's name, logo, flag or other branding requires prior permission from the Executive Committee.</p>", 3, "about", true, "about-logo", null, "Logo & Flag", null },
                    { 4, "<ul><li>To build and maintain a lasting bond among the alumni of Govt. Haraganga College.</li><li>To preserve and promote the heritage, history and traditions of the College.</li><li>To support the academic development of current students of the College.</li><li>To provide mentorship, career guidance and networking opportunities to students and alumni.</li><li>To assist alumni and students facing financial hardship through scholarships and welfare support.</li><li>To organise educational, cultural, social and sporting activities.</li><li>To encourage philanthropic and community service initiatives.</li><li>To strengthen cooperation between the Association, the College administration and its teachers.</li><li>To maintain an accurate register of alumni and facilitate communication among them.</li><li>To uphold transparency, accountability and good governance within the Association.</li><li>To undertake any other lawful activity consistent with these objectives.</li></ul>", 4, "about", true, "about-objectives", null, "Purpose & Objectives", null },
                    { 5, "<p>The Association's secretariat operates from the Govt. Haraganga College campus in Munshiganj. Reach us by email, phone, or the form below and a member of the Executive Committee will respond.</p>", 1, "contact", true, "contact-intro", null, "Get in Touch", null }
                });

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_SiteContents_Key"" ON ""SiteContents"" (""Key"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SiteContents");

            migrationBuilder.Sql(@"ALTER TABLE ""NewsPosts"" DROP COLUMN IF EXISTS ""AttachmentFileName"";");

            migrationBuilder.Sql(@"ALTER TABLE ""NewsPosts"" DROP COLUMN IF EXISTS ""AttachmentUrl"";");

            migrationBuilder.Sql(@"ALTER TABLE ""NewsPosts"" DROP COLUMN IF EXISTS ""PostType"";");
        }
    }
}
