platform :ios do
  desc "Push a new build to TestFlight"
  lane :beta do
    upload_to_testflight(
      app_identifier: "com.ghcaa.portal",
      ipa: "../build/ios/ipa/Haragangian.ipa",
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new build to the App Store"
  lane :release do
    upload_to_app_store(
      app_identifier: "com.ghcaa.portal",
      ipa: "../build/ios/ipa/Haragangian.ipa",
      submit_for_review: false,
      skip_screenshots: true
    )
  end
end
