platform :android do
  desc "Submit a new Internal Build to Google Play"
  lane :internal do
    upload_to_google_play(
      track: 'internal',
      package_name: 'com.ghcaa.portal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Submit a new Production Build to Google Play"
  lane :production do
    upload_to_google_play(
      track: 'production',
      package_name: 'com.ghcaa.portal',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
